# Generated by Django 4.2.20 on 2025-03-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoModoNoturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_ativacao', models.DateTimeField()),
                ('data_hora_desativacao', models.DateTimeField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, null=True)),
                ('ativado_automaticamente', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_modo_noturno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do Modo Noturno',
                'verbose_name_plural': 'Históricos do Modo Noturno',
                'ordering': ['-data_hora_ativacao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoModoNoturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('filtro_luz_azul_ativo', models.BooleanField(default=True)),
                ('intensidade_filtro', models.IntegerField(default=50, help_text='Intensidade do filtro de 0 a 100')),
                ('nao_perturbe_ativo', models.BooleanField(default=False)),
                ('horario_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('horario_fim', models.TimeField(default=django.utils.timezone.now)),
                ('silenciar_notificacoes', models.BooleanField(default=True)),
                ('permitir_chamadas_emergencia', models.BooleanField(default=True)),
                ('leitura_noturna_ativa', models.BooleanField(default=False)),
                ('tema_escuro', models.BooleanField(default=True)),
                ('tamanho_fonte', models.IntegerField(default=16)),
                ('contraste', models.IntegerField(default=50, help_text='Contraste de 0 a 100')),
                ('ativacao_automatica', models.BooleanField(default=False)),
                ('horario_ativacao', models.TimeField(default=django.utils.timezone.now)),
                ('horario_desativacao', models.TimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_modo_noturno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Modo Noturno',
                'verbose_name_plural': 'Configurações do Modo Noturno',
            },
        ),
    ]
