# Generated by Django 4.2.20 on 2025-03-10 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('saude', 'Saúde'), ('nutricao', 'Nutrição'), ('bem_estar', 'Bem-estar'), ('tecnologia', 'Tecnologia'), ('outro', 'Outro')], max_length=20)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('duracao_horas', models.IntegerField(help_text='Duração em horas')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now)),
                ('gratuito', models.BooleanField(default=False)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='ebooks/')),
                ('data_publicacao', models.DateField()),
                ('gratuito', models.BooleanField(default=False)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='ebooks/arquivos/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'E-book',
                'verbose_name_plural': 'E-books',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série'), ('documentario', 'Documentário')], max_length=20)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.IntegerField()),
                ('duracao_minutos', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('temporadas', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(max_length=100)),
                ('classificacao', models.CharField(max_length=10)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='midias/')),
                ('url_trailer', models.URLField(blank=True)),
                ('disponivel_em', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-ano_lancamento', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='promocoes/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('codigo_cupom', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['data_fim', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Videoaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('duracao_minutos', models.IntegerField(help_text='Duração em minutos')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videoaulas/')),
                ('url_video', models.URLField()),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now)),
                ('ordem', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoaulas', to='educacional.curso')),
            ],
            options={
                'verbose_name': 'Videoaula',
                'verbose_name_plural': 'Videoaulas',
                'ordering': ['curso', 'ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('concluida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('comprado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='educacional.listacompras')),
            ],
            options={
                'verbose_name': 'Item da Lista de Compras',
                'verbose_name_plural': 'Itens da Lista de Compras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('lembrete', models.BooleanField(default=True)),
                ('tempo_lembrete', models.IntegerField(default=30, help_text='Tempo em minutos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comentario', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='educacional.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_cursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição em Curso',
                'verbose_name_plural': 'Inscrições em Cursos',
                'ordering': ['-data_inscricao'],
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
