# Generated by Django 4.2.20 on 2025-03-12 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Playlist',
                'verbose_name_plural': 'Itens de Playlist',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série'), ('musica', 'Música'), ('jogo', 'Jogo'), ('podcast', 'Podcast'), ('outro', 'Outro')], max_length=20)),
                ('categoria', models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('ficcao', 'Ficção Científica'), ('terror', 'Terror'), ('romance', 'Romance'), ('documentario', 'Documentário'), ('animacao', 'Animação'), ('esporte', 'Esporte'), ('musical', 'Musical'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('ano_lancamento', models.IntegerField()),
                ('duracao_minutos', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='midias/')),
                ('link_streaming', models.URLField(blank=True)),
                ('artista_autor', models.CharField(blank=True, max_length=200)),
                ('classificacao', models.CharField(blank=True, max_length=10)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-data_adicao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('publica', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('midias', models.ManyToManyField(related_name='playlists', through='entretenimento.ItemPlaylist', to='entretenimento.midia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.AddField(
            model_name='itemplaylist',
            name='midia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_playlist', to='entretenimento.midia'),
        ),
        migrations.AddField(
            model_name='itemplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='entretenimento.playlist'),
        ),
        migrations.CreateModel(
            name='HistoricoReproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reproducao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tempo_assistido', models.IntegerField(default=0, help_text='Tempo assistido em segundos')),
                ('concluido', models.BooleanField(default=False)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_reproducao', to='entretenimento.midia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_reproducao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Reprodução',
                'verbose_name_plural': 'Históricos de Reprodução',
                'ordering': ['-data_reproducao'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemplaylist',
            unique_together={('playlist', 'midia')},
        ),
    ]
