# Generated by Django 4.2.20 on 2025-03-12 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacional', '0002_evento_lista_compras_evento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('lista_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='educacional.listacompras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('alimentos', 'Alimentos'), ('vestuario', 'Vestuário'), ('casa_decoracao', 'Casa e Decoração'), ('saude_beleza', 'Saúde e Beleza'), ('esportes', 'Esportes e Lazer'), ('brinquedos', 'Brinquedos'), ('livros', 'Livros'), ('outro', 'Outro')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PromocaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('desconto', models.DecimalField(decimal_places=2, help_text='Valor do desconto em porcentagem', max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='promocoes_produtos/')),
                ('codigo_cupom', models.CharField(blank=True, max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='mercado.produto')),
            ],
            options={
                'verbose_name': 'Promoção de Produto',
                'verbose_name_plural': 'Promoções de Produtos',
                'ordering': ['data_fim', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mercado.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='mercado.produto')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Itens de Compra',
            },
        ),
    ]
