# Generated by Django 4.2.20 on 2025-03-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoagua',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
