# Generated by Django 4.2.20 on 2025-03-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marmita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('fitness', 'Fitness'), ('vegetariana', 'Vegetariana'), ('geral', 'Geral')], max_length=20)),
                ('tipo_refeicao', models.CharField(choices=[('cafe_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('sobremesa', 'Sobremesa'), ('lanche', 'Lanche')], max_length=20)),
                ('calorias', models.IntegerField(help_text='Valor calórico em kcal')),
                ('proteinas', models.DecimalField(decimal_places=2, help_text='Quantidade em gramas', max_digits=5)),
                ('carboidratos', models.DecimalField(decimal_places=2, help_text='Quantidade em gramas', max_digits=5)),
                ('gorduras', models.DecimalField(decimal_places=2, help_text='Quantidade em gramas', max_digits=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='marmitas/')),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marmita',
                'verbose_name_plural': 'Marmitas',
                'ordering': ['categoria', 'tipo_refeicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('objetivo', models.CharField(max_length=100)),
                ('restricoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_alimentares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Alimentar',
                'verbose_name_plural': 'Planos Alimentares',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='nutricao.marmita')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nutricao.planoalimentar')),
            ],
            options={
                'verbose_name': 'Item do Plano Alimentar',
                'verbose_name_plural': 'Itens do Plano Alimentar',
                'ordering': ['dia_semana', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoMarmita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='nutricao.marmita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_marmita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Marmita',
                'verbose_name_plural': 'Avaliações de Marmitas',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('usuario', 'marmita')},
            },
        ),
    ]
